
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: ""
            tests:
                - unique
                - not_null
          - name: EMPNO
            description: ""
            tests:
                - unique
          - name: CONTACT_NO
            description: ""
            tests:
                - unique
          - name: EMAIL_ADDRESS
            description: ""
            tests:
                - unique


