
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: Leads
            description: ""
            tests:
                - unique
                - not_null
          - name: EMPNO
            description: ""
            tests:
                - unique


